version: "3"

services:
  api:
    build: ./api/
    ports:
      - "3000:3000"
  smtp:
    build: ./smtp/
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=upserveradmin
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-db:/etc/todos/test.db
      - ./postgres-db:/root/testFolder/